-- ============== SCHEMA ==============

CREATE TABLE IF NOT EXISTS employees (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS code_table (
  code TEXT PRIMARY KEY,
  day_label TEXT,
  night_label TEXT
);

CREATE TABLE IF NOT EXISTS seat_template (
  seat INTEGER NOT NULL,
  dow TEXT NOT NULL,
  period TEXT,
  code TEXT,
  PRIMARY KEY (seat, dow)
);

CREATE TABLE IF NOT EXISTS anchor_week (
  emp_id INTEGER PRIMARY KEY,
  seat INTEGER NOT NULL,
  grp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS shifts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  dow TEXT NOT NULL,
  emp_id INTEGER NOT NULL,
  emp_name TEXT NOT NULL,
  period TEXT NOT NULL,
  code TEXT NOT NULL,
  label TEXT NOT NULL,
  swappable INTEGER NOT NULL DEFAULT 1,
  UNIQUE(date, emp_id)
);
CREATE INDEX IF NOT EXISTS idx_shifts_date ON shifts(date);
CREATE INDEX IF NOT EXISTS idx_shifts_emp ON shifts(emp_id);

CREATE TABLE IF NOT EXISTS swap_requests (
  id TEXT PRIMARY KEY,
  created_at TEXT NOT NULL,
  requester_id INTEGER NOT NULL,
  requester_name TEXT NOT NULL,
  target_id INTEGER NOT NULL,
  target_name TEXT NOT NULL,
  my_date TEXT NOT NULL,
  my_dow TEXT NOT NULL,
  my_code TEXT NOT NULL,
  my_period TEXT NOT NULL,
  target_date TEXT NOT NULL,
  target_dow TEXT NOT NULL,
  target_code TEXT NOT NULL,
  target_period TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT '대기',
  memo TEXT,
  processed_at TEXT
);

-- ============== SEED: employees ==============
INSERT INTO employees (id, name, active) VALUES (1, '김익태', 1);
INSERT INTO employees (id, name, active) VALUES (2, '심용남', 1);
INSERT INTO employees (id, name, active) VALUES (3, '신봉식', 1);
INSERT INTO employees (id, name, active) VALUES (4, '전문일', 1);
INSERT INTO employees (id, name, active) VALUES (5, '박봉권', 1);
INSERT INTO employees (id, name, active) VALUES (6, '이동운', 1);
INSERT INTO employees (id, name, active) VALUES (7, '윤재용', 1);
INSERT INTO employees (id, name, active) VALUES (8, '엄동진', 1);
INSERT INTO employees (id, name, active) VALUES (9, '이성석', 1);
INSERT INTO employees (id, name, active) VALUES (10, '강규영', 1);
INSERT INTO employees (id, name, active) VALUES (11, '김민숙', 1);
INSERT INTO employees (id, name, active) VALUES (12, '이병태', 1);
INSERT INTO employees (id, name, active) VALUES (13, '차기훈', 1);
INSERT INTO employees (id, name, active) VALUES (14, '이승준', 1);
INSERT INTO employees (id, name, active) VALUES (15, '김신효', 1);
INSERT INTO employees (id, name, active) VALUES (16, '이상용', 1);
INSERT INTO employees (id, name, active) VALUES (17, '유기민', 1);
INSERT INTO employees (id, name, active) VALUES (18, '김호경', 1);
INSERT INTO employees (id, name, active) VALUES (19, '최창용', 1);
INSERT INTO employees (id, name, active) VALUES (20, '임비호', 1);
INSERT INTO employees (id, name, active) VALUES (21, '김동현', 1);
INSERT INTO employees (id, name, active) VALUES (22, '박정민', 1);
INSERT INTO employees (id, name, active) VALUES (23, '김성식', 1);
INSERT INTO employees (id, name, active) VALUES (24, '정주훈', 1);
INSERT INTO employees (id, name, active) VALUES (25, '양범준', 0);
INSERT INTO employees (id, name, active) VALUES (26, '박상숙', 1);
INSERT INTO employees (id, name, active) VALUES (27, '허상회', 1);
INSERT INTO employees (id, name, active) VALUES (28, '이연숙', 1);
INSERT INTO employees (id, name, active) VALUES (29, '김선겸', 1);
INSERT INTO employees (id, name, active) VALUES (30, '김창현', 1);
INSERT INTO employees (id, name, active) VALUES (31, '방현주', 1);
INSERT INTO employees (id, name, active) VALUES (32, '김성동', 1);
INSERT INTO employees (id, name, active) VALUES (33, '이종권', 1);
INSERT INTO employees (id, name, active) VALUES (34, '배재영', 1);
INSERT INTO employees (id, name, active) VALUES (35, '강병희', 1);
-- ============== SEED: code_table ==============
INSERT INTO code_table (code, day_label, night_label) VALUES ('1', '주간1', '야간1');
INSERT INTO code_table (code, day_label, night_label) VALUES ('1A', '주간1A', '야간1A');
INSERT INTO code_table (code, day_label, night_label) VALUES ('1B', '주간1B', '야간1B');
INSERT INTO code_table (code, day_label, night_label) VALUES ('1C', '주간1C', '야간1C');
INSERT INTO code_table (code, day_label, night_label) VALUES ('1D', '주간1D', '야간1D');
INSERT INTO code_table (code, day_label, night_label) VALUES ('3', '주간3', '야간3');
INSERT INTO code_table (code, day_label, night_label) VALUES ('3A', '주간3A', '야간3A');
INSERT INTO code_table (code, day_label, night_label) VALUES ('3B', '주간3B', '야간3B');
INSERT INTO code_table (code, day_label, night_label) VALUES ('5', '주간5', '야간5');
INSERT INTO code_table (code, day_label, night_label) VALUES ('5A', '주간5A', '야간5A');
INSERT INTO code_table (code, day_label, night_label) VALUES ('N', '주간N', NULL);
INSERT INTO code_table (code, day_label, night_label) VALUES ('N1', '주간N1', NULL);
INSERT INTO code_table (code, day_label, night_label) VALUES ('R', '주간R', '야간R');
INSERT INTO code_table (code, day_label, night_label) VALUES ('R1', '주간R1', '야간R1');
-- ============== SEED: seat_template ==============
INSERT INTO seat_template (seat, dow, period, code) VALUES (1, '월', '주간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (1, '화', '야간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (1, '수', '야간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (1, '목', '야간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (1, '금', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (1, '토', '주간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (1, '일', '주간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (2, '월', '주간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (2, '화', '주간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (2, '수', '주간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (2, '목', '야간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (2, '금', '야간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (2, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (2, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (3, '월', '주간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (3, '화', '주간', 'N');
INSERT INTO seat_template (seat, dow, period, code) VALUES (3, '수', '야간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (3, '목', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (3, '금', '주간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (3, '토', '주간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (3, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (4, '월', '야간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (4, '화', '야간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (4, '수', '야간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (4, '목', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (4, '금', '주간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (4, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (4, '일', '야간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (5, '월', '야간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (5, '화', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (5, '수', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (5, '목', '주간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (5, '금', '주간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (5, '토', '야간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (5, '일', '야간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (6, '월', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (6, '화', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (6, '수', '주간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (6, '목', '주간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (6, '금', '야간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (6, '토', '야간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (6, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (7, '월', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (7, '화', '주간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (7, '수', '주간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (7, '목', '주간', 'N');
INSERT INTO seat_template (seat, dow, period, code) VALUES (7, '금', '야간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (7, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (7, '일', '주간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (8, '월', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (8, '화', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (8, '수', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (8, '목', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (8, '금', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (8, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (8, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (9, '월', '야간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (9, '화', '야간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (9, '수', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (9, '목', '야간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (9, '금', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (9, '토', '주간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (9, '일', '야간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (10, '월', '야간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (10, '화', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (10, '수', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (10, '목', '주간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (10, '금', '주간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (10, '토', '야간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (10, '일', '야간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (11, '월', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (11, '화', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (11, '수', '주간', 'N');
INSERT INTO seat_template (seat, dow, period, code) VALUES (11, '목', '주간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (11, '금', '야간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (11, '토', '야간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (11, '일', '야간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (12, '월', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (12, '화', '주간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (12, '수', '주간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (12, '목', '야간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (12, '금', '야간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (12, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (12, '일', '주간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (13, '월', '주간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (13, '화', '주간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (13, '수', '야간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (13, '목', '야간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (13, '금', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (13, '토', '주간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (13, '일', '주간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (14, '월', '주간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (14, '화', '야간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (14, '수', '야간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (14, '목', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (14, '금', '주간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (14, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (14, '일', '주간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (15, '월', '야간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (15, '화', '야간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (15, '수', '야간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (15, '목', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (15, '금', '주간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (15, '토', '주간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (15, '일', '야간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (16, '월', '야간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (16, '화', '야간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (16, '수', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (16, '목', '주간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (16, '금', '주간', 'N');
INSERT INTO seat_template (seat, dow, period, code) VALUES (16, '토', '야간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (16, '일', '야간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (17, '월', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (17, '화', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (17, '수', '주간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (17, '목', '주간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (17, '금', '야간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (17, '토', '야간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (17, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (18, '월', '주간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (18, '화', '주간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (18, '수', '주간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (18, '목', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (18, '금', '주간', '1B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (18, '토', '주간', '3');
INSERT INTO seat_template (seat, dow, period, code) VALUES (18, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (19, '월', '주간', 'N');
INSERT INTO seat_template (seat, dow, period, code) VALUES (19, '화', '주간', '1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (19, '수', '주간', 'R');
INSERT INTO seat_template (seat, dow, period, code) VALUES (19, '목', '야간', '1A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (19, '금', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (19, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (19, '일', '주간', '5');
INSERT INTO seat_template (seat, dow, period, code) VALUES (20, '월', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (20, '화', '주간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (20, '수', '주간', 'N1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (20, '목', '야간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (20, '금', '야간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (20, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (20, '일', '주간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (21, '월', '야간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (21, '화', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (21, '수', '주간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (21, '목', '주간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (21, '금', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (21, '토', '주간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (21, '일', '주간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (22, '월', '주간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (22, '화', '야간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (22, '수', '야간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (22, '목', '야간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (22, '금', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (22, '토', '주간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (22, '일', '주간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (23, '월', '주간', 'N1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (23, '화', '주간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (23, '수', '야간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (23, '목', '야간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (23, '금', '야간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (23, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (23, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (24, '월', '주간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (24, '화', '야간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (24, '수', '야간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (24, '목', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (24, '금', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (24, '토', '주간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (24, '일', '야간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (25, '월', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (25, '화', '주간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (25, '수', '주간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (25, '목', '주간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (25, '금', '주간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (25, '토', '야간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (25, '일', '야간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (26, '월', '주간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (26, '화', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (26, '수', '야간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (26, '목', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (26, '금', '주간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (26, '토', '주간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (26, '일', '야간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (27, '월', '야간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (27, '화', '야간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (27, '수', '야간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (27, '목', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (27, '금', '주간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (27, '토', '주간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (27, '일', '야간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (28, '월', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (28, '화', '주간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (28, '수', '주간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (28, '목', '주간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (28, '금', '야간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (28, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (28, '일', '주간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (29, '월', '야간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (29, '화', '야간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (29, '수', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (29, '목', '주간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (29, '금', '주간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (29, '토', '주간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (29, '일', '야간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (30, '월', '주간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (30, '화', '주간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (30, '수', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (30, '목', '야간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (30, '금', '야간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (30, '토', '야간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (30, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (31, '월', '야간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (31, '화', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (31, '수', '주간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (31, '목', '주간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (31, '금', '야간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (31, '토', '야간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (31, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (32, '월', '주간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (32, '화', '주간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (32, '수', '주간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (32, '목', '야간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (32, '금', '야간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (32, '토', '야간', '1C');
INSERT INTO seat_template (seat, dow, period, code) VALUES (32, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (33, '월', '야간', '3A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (33, '화', '야간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (33, '수', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (33, '목', '주간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (33, '금', '주간', 'N1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (33, '토', '야간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (33, '일', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (34, '월', '주간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (34, '화', '주간', 'N1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (34, '수', '야간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (34, '목', '야간', '1D');
INSERT INTO seat_template (seat, dow, period, code) VALUES (34, '금', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (34, '토', '야간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (34, '일', '주간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (35, '월', '야간', 'R1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (35, '화', '야간', '5A');
INSERT INTO seat_template (seat, dow, period, code) VALUES (35, '수', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (35, '목', '주간', 'N1');
INSERT INTO seat_template (seat, dow, period, code) VALUES (35, '금', '주간', '3B');
INSERT INTO seat_template (seat, dow, period, code) VALUES (35, '토', NULL, NULL);
INSERT INTO seat_template (seat, dow, period, code) VALUES (35, '일', '주간', '3B');
-- ============== SEED: anchor_week ==============
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (18, 1, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (1, 2, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (2, 3, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (3, 4, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (4, 5, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (5, 6, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (6, 7, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (7, 9, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (8, 10, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (9, 11, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (10, 12, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (11, 13, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (12, 14, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (13, 15, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (14, 16, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (15, 17, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (16, 18, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (17, 19, 'A');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (34, 20, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (19, 21, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (20, 22, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (21, 23, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (22, 24, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (23, 25, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (24, 26, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (35, 27, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (26, 28, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (27, 29, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (28, 30, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (29, 31, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (30, 32, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (31, 33, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (32, 34, 'B');
INSERT INTO anchor_week (emp_id, seat, grp) VALUES (33, 35, 'B');
-- ============== SEED: shifts ==============
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 1, '김익태', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 2, '심용남', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 3, '신봉식', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 12, '이병태', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 13, '차기훈', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 17, '유기민', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 18, '김호경', '주간', 'N', '주간N', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 21, '김동현', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 22, '박정민', '주간', 'N1', '주간N1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 23, '김성식', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 25, '양범준', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 29, '김선겸', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 31, '방현주', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 33, '이종권', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 4, '전문일', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 5, '박봉권', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 8, '엄동진', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 9, '이성석', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 14, '이승준', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 15, '김신효', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 20, '임비호', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 26, '박상숙', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 28, '이연숙', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 30, '김창현', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 32, '김성동', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-24', '월', 34, '배재영', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 2, '심용남', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 3, '신봉식', '주간', 'N', '주간N', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 7, '윤재용', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 11, '김민숙', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 12, '이병태', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 17, '유기민', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 18, '김호경', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 19, '최창용', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 22, '박정민', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 24, '정주훈', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 27, '허상회', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 29, '김선겸', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 31, '방현주', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 33, '이종권', '주간', 'N1', '주간N1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 1, '김익태', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 4, '전문일', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 8, '엄동진', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 13, '차기훈', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 14, '이승준', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 15, '김신효', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 21, '김동현', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 23, '김성식', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 26, '박상숙', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 28, '이연숙', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 32, '김성동', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-25', '화', 34, '배재영', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 2, '심용남', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 6, '이동운', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 7, '윤재용', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 10, '강규영', '주간', 'N', '주간N', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 11, '김민숙', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 16, '이상용', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 17, '유기민', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 18, '김호경', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 19, '최창용', '주간', 'N1', '주간N1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 20, '임비호', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 24, '정주훈', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 27, '허상회', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 30, '김창현', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 31, '방현주', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 1, '김익태', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 3, '신봉식', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 4, '전문일', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 12, '이병태', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 13, '차기훈', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 14, '이승준', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 21, '김동현', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 22, '박정민', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 23, '김성식', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 25, '양범준', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 26, '박상숙', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-26', '수', 33, '이종권', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 5, '박봉권', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 6, '이동운', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 7, '윤재용', '주간', 'N', '주간N', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 9, '이성석', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 10, '강규영', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 15, '김신효', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 16, '이상용', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 20, '임비호', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 24, '정주훈', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 27, '허상회', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 28, '이연숙', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 30, '김창현', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 32, '김성동', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 34, '배재영', '주간', 'N1', '주간N1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 1, '김익태', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 2, '심용남', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 8, '엄동진', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 11, '김민숙', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 12, '이병태', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 18, '김호경', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 19, '최창용', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 21, '김동현', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 22, '박정민', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 29, '김선겸', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 31, '방현주', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-27', '목', 33, '이종권', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 3, '신봉식', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 4, '전문일', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 5, '박봉권', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 9, '이성석', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 13, '차기훈', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 14, '이승준', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 15, '김신효', '주간', 'N', '주간N', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 17, '유기민', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 24, '정주훈', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 25, '양범준', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 26, '박상숙', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 28, '이연숙', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 32, '김성동', '주간', 'N1', '주간N1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 34, '배재영', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 2, '심용남', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 6, '이동운', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 7, '윤재용', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 10, '강규영', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 11, '김민숙', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 16, '이상용', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 19, '최창용', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 22, '박정민', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 27, '허상회', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 29, '김선겸', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 30, '김창현', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-28', '금', 31, '방현주', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 1, '김익태', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 3, '신봉식', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 8, '엄동진', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 12, '이병태', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 14, '이승준', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 17, '유기민', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 20, '임비호', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 21, '김동현', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 23, '김성식', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 25, '양범준', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 26, '박상숙', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 28, '이연숙', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 5, '박봉권', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 6, '이동운', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 9, '이성석', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 10, '강규영', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 15, '김신효', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 16, '이상용', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 24, '정주훈', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 29, '김선겸', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 30, '김창현', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 31, '방현주', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 32, '김성동', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-29', '토', 33, '이종권', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 1, '김익태', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 7, '윤재용', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 11, '김민숙', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 12, '이병태', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 13, '차기훈', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 18, '김호경', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 19, '최창용', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 20, '임비호', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 21, '김동현', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 27, '허상회', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 33, '이종권', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 34, '배재영', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 4, '전문일', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 5, '박봉권', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 8, '엄동진', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 9, '이성석', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 10, '강규영', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 14, '이승준', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 15, '김신효', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 23, '김성식', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 24, '정주훈', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 25, '양범준', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 26, '박상숙', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-30', '일', 28, '이연숙', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 18, '김호경', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 1, '김익태', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 2, '심용남', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 11, '김민숙', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 12, '이병태', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 16, '이상용', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 17, '유기민', '주간', 'N', '주간N', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 20, '임비호', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 21, '김동현', '주간', 'N1', '주간N1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 22, '박정민', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 24, '정주훈', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 28, '이연숙', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 30, '김창현', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 32, '김성동', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 3, '신봉식', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 4, '전문일', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 7, '윤재용', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 8, '엄동진', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 13, '차기훈', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 14, '이승준', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 19, '최창용', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 35, '강병희', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 27, '허상회', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 29, '김선겸', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 31, '방현주', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-08-31', '월', 33, '이종권', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 1, '김익태', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 2, '심용남', '주간', 'N', '주간N', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 6, '이동운', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 10, '강규영', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 11, '김민숙', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 16, '이상용', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 17, '유기민', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 34, '배재영', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 21, '김동현', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 23, '김성식', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 26, '박상숙', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 28, '이연숙', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 30, '김창현', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 32, '김성동', '주간', 'N1', '주간N1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 18, '김호경', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 3, '신봉식', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 7, '윤재용', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 12, '이병태', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 13, '차기훈', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 14, '이승준', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 20, '임비호', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 22, '박정민', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 35, '강병희', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 27, '허상회', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 31, '방현주', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-01', '화', 33, '이종권', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 1, '김익태', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 5, '박봉권', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 6, '이동운', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 9, '이성석', '주간', 'N', '주간N', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 10, '강규영', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 15, '김신효', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 16, '이상용', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 17, '유기민', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 34, '배재영', '주간', 'N1', '주간N1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 19, '최창용', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 23, '김성식', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 26, '박상숙', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 29, '김선겸', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 30, '김창현', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 18, '김호경', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 2, '심용남', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 3, '신봉식', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 11, '김민숙', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 12, '이병태', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 13, '차기훈', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 20, '임비호', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 21, '김동현', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 22, '박정민', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 24, '정주훈', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 35, '강병희', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-02', '수', 32, '김성동', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 4, '전문일', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 5, '박봉권', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 6, '이동운', '주간', 'N', '주간N', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 8, '엄동진', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 9, '이성석', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 14, '이승준', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 15, '김신효', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 19, '최창용', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 23, '김성식', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 26, '박상숙', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 27, '허상회', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 29, '김선겸', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 31, '방현주', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 33, '이종권', '주간', 'N1', '주간N1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 18, '김호경', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 1, '김익태', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 7, '윤재용', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 10, '강규영', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 11, '김민숙', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 17, '유기민', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 34, '배재영', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 20, '임비호', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 21, '김동현', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 28, '이연숙', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 30, '김창현', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-03', '목', 32, '김성동', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 2, '심용남', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 3, '신봉식', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 4, '전문일', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 8, '엄동진', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 12, '이병태', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 13, '차기훈', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 14, '이승준', '주간', 'N', '주간N', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 16, '이상용', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 23, '김성식', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 24, '정주훈', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 35, '강병희', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 27, '허상회', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 31, '방현주', '주간', 'N1', '주간N1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 33, '이종권', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 1, '김익태', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 5, '박봉권', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 6, '이동운', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 9, '이성석', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 10, '강규영', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 15, '김신효', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 34, '배재영', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 21, '김동현', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 26, '박상숙', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 28, '이연숙', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 29, '김선겸', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-04', '금', 30, '김창현', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 18, '김호경', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 2, '심용남', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 7, '윤재용', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 11, '김민숙', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 13, '차기훈', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 16, '이상용', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 19, '최창용', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 20, '임비호', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 22, '박정민', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 24, '정주훈', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 35, '강병희', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 27, '허상회', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 4, '전문일', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 5, '박봉권', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 8, '엄동진', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 9, '이성석', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 14, '이승준', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 15, '김신효', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 23, '김성식', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 28, '이연숙', '야간', '3A', '야간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 29, '김선겸', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 30, '김창현', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 31, '방현주', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-05', '토', 32, '김성동', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 18, '김호경', '주간', '1B', '주간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 6, '이동운', '주간', '1A', '주간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 10, '강규영', '주간', '1', '주간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 11, '김민숙', '주간', 'R', '주간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 12, '이병태', '주간', '3', '주간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 17, '유기민', '주간', '5', '주간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 34, '배재영', '주간', '1D', '주간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 19, '최창용', '주간', '3A', '주간3A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 20, '임비호', '주간', '1C', '주간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 26, '박상숙', '주간', '5A', '주간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 32, '김성동', '주간', 'R1', '주간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 33, '이종권', '주간', '3B', '주간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 3, '신봉식', '야간', '1', '야간1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 4, '전문일', '야간', '1B', '야간1B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 7, '윤재용', '야간', '3', '야간3', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 8, '엄동진', '야간', 'R', '야간R', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 9, '이성석', '야간', 'R1', '야간R1', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 13, '차기훈', '야간', '5', '야간5', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 14, '이승준', '야간', '1A', '야간1A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 22, '박정민', '야간', '1C', '야간1C', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 23, '김성식', '야간', '3B', '야간3B', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 24, '정주훈', '야간', '5A', '야간5A', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 35, '강병희', '야간', '1D', '야간1D', 1);
INSERT INTO shifts (date, dow, emp_id, emp_name, period, code, label, swappable) VALUES ('2026-09-06', '일', 27, '허상회', '야간', '3A', '야간3A', 1);